### ISSUE TITLE
Mentioning AMI in the docs

### ISSUE THREAD

**Issue by unfor19** [aws-samples/aws-ab-util#1]
Thank you for this tool, it works as expected.

Other than creating the IAM role, I think it would be great to add something about the AMI, or maybe even allow providing it as an environment variable. I edited the code and hardcoded the AMI for eu-west-1.

Also, would you be interested in a PR that wraps it up in a Docker image? I can also add a script for creating the SSMInstanceProfile IAM role (and policy).

**Comment by tgpadua** [comment]
Hello @unfor19, I appreciate your interest in the tool.

Correct, in the previous version AMI was hard-coded and you had to edit the code as you did. The good news is that I've just commited a new version which automatically select the last Amazon Linux AMI based on the region configured in your AWS CLI config. Please check it out!

Absolutely, it would be very nice to have the IAM role creation automated, feel free to send me a PR.

Could you please elaborate more on the use case to have this wrapped in a Docker image? I mean, are you considering to run it using a runtime like Fargate, ECS or EKS instead of EC2? If so, how would the script manage it?

PS: This new version also includes a new feature (cmd) that allows you to execute any command you want.

Thanks!
Thiago

**Comment by unfor19** [comment]
Hey @tgpadua 

- IAM role creation - I'll add a PR for that, something like "--create-iam-role=true" where it defaults to false.
- Docker image - I tend to run everything in Docker, especially bash scripts that require specific versions of specific tools. For example - this tool works for aws-cli v2.20.x (just an example) but might break in v2.30.x, so wrapping it up in a Docker image assures that it will never break, and the worst thing that will happen - it will be deprecated due to old versions. It's easier to just work with Docker ... No hassle at all, a simple `docker run` and that's it

Here's how I usually wrap a Bash script as a CLI - https://github.com/unfor19/bargs
